const helperReport = {
    headerSalesReport: [
        'no',
        'invoice',
        'date',
        'users',
        'sub-total',
        'discount',
        'total',
    ],
    headerPurchasesReport: [
        'no',
        'invoice',
        'date',
        'users',
        'sub-total',
        'discount',
        'total',
    ],
    headerMarginsReport: [
        'no',
        'invoice',
        'date',
        'capital',
        'sell',
        'margin',
    ],
    headerBestSellerReport: [
        'no',
        'product',
        'category',
        'quantity',
        'total',
    ],
    headerStockOpnameReport: [
        'no',
        'date',
        'product',
        'system-stock',
        'actual-stock',
        'difference',
    ],
    headerAttendanceReport: [
        'no',
        'date',
        'employee',
        'check-in',
        'check-out',
        'status',
    ],
    headerAccountancyReport: [
        'no',
        'date',
        'account',
        'debit',
        'credit',
        'balance',
    ],
    headerAccountBalanceReport: [
        'no',
        'account',
        'balance',
    ],
    headerTransferReport: [
        'no',
        'date',
        'from',
        'to',
        'amount',
    ],
    headerCashInReport: [
        'no',
        'date',
        'account',
        'amount',
        'description',
    ],
    headerCashOutReport: [
        'no',
        'date',
        'account',
        'amount',
        'description',
    ],
    headerExpenseReport: [
        'no',
        'date',
        'account',
        'amount',
        'description',
    ]
}

export default helperReport