const url = {
    Dashboard: {
        sales: 'dashboards/sale',
        saleStockist: 'dashboards/sale-stockist',
        point: 'dashboards/point',
        package: 'dashboards/package'
    },
    Address: {
        province: 'address/province',
        city: 'address/cities',
        district: 'address/districts',
    },
    auth: {
        login:'auth/login',
        forgotPassword: 'auth/forgot-password'
    },
    User: {
        get: 'users',
        post: 'users',
        put: 'users',
        getById: 'users',
        delete: 'users',
        getSelect: 'users/get-select',
        getStockistSelect: 'users/get-stockist-select',
    },
    Reward: {
        get: 'rewards',
        post: 'rewards',
        put: 'rewards',
        getById: 'rewards',
        delete: 'rewards',
        getSelect: 'rewards/get-select',
    },
    BankAccount: {
        get: 'bank-accounts',
        post: 'bank-accounts',
        put: 'bank-accounts',
        getById: 'bank-accounts',
        delete: 'bank-accounts',
        getSelect: 'bank-accounts/select',
    },
    ProductCategory: {
        get: 'product-categories',
        post: 'product-categories',
        put: 'product-categories',
        getById: 'product-categories',
        delete: 'product-categories',
        getSelect: 'product-categories/select',
    },
    Product: {
        get: 'products',
        post: 'products',
        put: 'products',
        getById: 'products',
        delete: 'products',
        getPrice: 'products/price',
        getSelect: 'products/get-select',
    },
    AgenType: {
        get: 'agen-types',
        post: 'agen-types',
        put: 'agen-types',
        getById: 'agen-types',
        delete: 'agen-types',
        getSelect: 'agen-types/select',
    },
    Member: {
        get: 'members',
        post: 'members',
        put: 'members',
        getById: 'members',
        delete: 'members',
        getSelect: 'members/select',
    },
    ClaimPoints: {
        get: 'claim-points',
        post: 'claim-points',
        put: 'claim-points',
        getById: 'claim-points',
        delete: 'claim-points',
        checkPoint: 'claim-points/point',
        getSelect: 'claim-points/select',
        download: 'claim-points/download',
    },
    ClaimRewards: {
        get: 'claim-rewards',
        post: 'claim-rewards',
        put: 'claim-rewards',
        getById: 'claim-rewards',
        delete: 'claim-rewards',
        lastClaim: 'claim-rewards/last',
        checkPoint: 'claim-rewards/point',
        getSelect: 'claim-rewards/select',
        download: 'claim-rewards/download'
    },
    Warehouse: {
        get: 'warehouses',
        post: 'warehouses',
        put: 'warehouses',
        getById: 'warehouses',
        delete: 'warehouses',
        getSelect: 'warehouses/select',
    },
    Sale: {
        get: 'sales',
        post: 'sales',
        put: 'sales',
        getById: 'sales',
        delete: 'sales',
        getSelect: 'sales/select',
    },
    SaleStockist: {
        get: 'sale-stockists',
        post: 'sale-stockists',
        put: 'sale-stockists',
        getById: 'sale-stockists',
        delete: 'sale-stockists',
        getSelect: 'sale-stockists/select',
    },
    Report: {
        salesReport: 'sales-report',
        salesReportExportExcel: 'sales-report/export-excel',
        salesReportDownload: 'sales-report/download',
        pointsReport: 'points-report',
        userPointsReport: 'users-points-report',
        claimPointsReport: 'claim-points-report',
        claimRewardsReport: 'claim-rewards-report',
    },
    Setting: {
        warehouse: 'warehouse',
        post: 'settings',
        get: 'settings',
    }
};

export default url